name: Azure ARM

on:
  push:      
     branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
      - name: Run ARM deploy
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./logiapp.json
          parameters: 
              name=logicapp019923
              location=northeurope

     # send email
      - name: Send Email
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'GitHub Action Notification'
          body: 'Workflow for resource deployment completed successfully!'
          to: 'bibekbarik81@outlook.com'
          from: 'bibekbarik81@gmail.com'
          secure: false


